# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/hp/Desktop/hassan_ai/dot_product_sim/dot_product_sim.srcs/sources_1/ip/floating_point_1/floating_point_1.xci
# IP: The module: 'floating_point_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hp/Desktop/hassan_ai/dot_product_sim/dot_product_sim.gen/sources_1/ip/floating_point_1/floating_point_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/hp/Desktop/hassan_ai/dot_product_sim/dot_product_sim.srcs/sources_1/ip/floating_point_1/floating_point_1.xci
# IP: The module: 'floating_point_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hp/Desktop/hassan_ai/dot_product_sim/dot_product_sim.gen/sources_1/ip/floating_point_1/floating_point_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
