#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu May 01 12:18:33 EDT 2025
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_top_dot_product_engine_multi_behav -key {Behavioral:sim_1:Functional:tb_top_dot_product_engine_multi} -tclbatch tb_top_dot_product_engine_multi.tcl -view /home/hp/Desktop/hassan_ai/dot_product_sim/tb_dot_product_engine_fp_behav.wcfg -log simulate.log"
xsim tb_top_dot_product_engine_multi_behav -key {Behavioral:sim_1:Functional:tb_top_dot_product_engine_multi} -tclbatch tb_top_dot_product_engine_multi.tcl -view /home/hp/Desktop/hassan_ai/dot_product_sim/tb_dot_product_engine_fp_behav.wcfg -log simulate.log

