#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon May 12 02:22:49 EDT 2025
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_top_dot_product_engine_behav -key {Behavioral:sim_1:Functional:tb_top_dot_product_engine} -tclbatch tb_top_dot_product_engine.tcl -view /home/hp/Desktop/hassan_ai/dpe_git/dot_product_integration/tb_dot_product_engine_fp_behav.wcfg -log simulate.log"
xsim tb_top_dot_product_engine_behav -key {Behavioral:sim_1:Functional:tb_top_dot_product_engine} -tclbatch tb_top_dot_product_engine.tcl -view /home/hp/Desktop/hassan_ai/dpe_git/dot_product_integration/tb_dot_product_engine_fp_behav.wcfg -log simulate.log

